import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';

async function scrapeBanners() {
  console.log('Starting browser...');
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
  const page = await browser.newPage();

  console.log('Navigating to uma.moe/timeline...');
  await page.goto('https://uma.moe/timeline', { waitUntil: 'networkidle2' });

  // Wait for the timeline to render
  await page.waitForSelector('.timeline-container, mat-card', { timeout: 10000 });

  console.log('Scraping data...');
  const banners = await page.evaluate(() => {
    const items = [];
    const cards = document.querySelectorAll('mat-card');

    cards.forEach(card => {
      const typeElement = card.querySelector('.category-tag') || card.querySelector('.mat-mdc-card-header-text');
      const titleElement = card.querySelector('.mat-mdc-card-title') || card.querySelector('h3');
      const dateElement = card.querySelector('.date-text') || card.querySelector('.temporal-info');
      const imgElement = card.querySelector('img');
      
      // Attempt to extract more specific info
      const typeText = typeElement?.textContent?.trim() || '';
      const title = titleElement?.textContent?.trim() || '';
      const dateRange = dateElement?.textContent?.trim() || '';
      const imageUrl = imgElement?.src || '';

      // Determine type
      let type = 'Other';
      if (typeText.toLowerCase().includes('character')) type = 'Character Banner';
      else if (typeText.toLowerCase().includes('support')) type = 'Support Card Banner';
      else if (typeText.toLowerCase().includes('story')) type = 'Story Event';
      else if (typeText.toLowerCase().includes('mission')) type = 'Campaign';

      // Basic date parsing (e.g. "Jun 27 - Jul 10")
      // In a real scenario, we might want more robust parsing
      
      items.push({
        id: Math.random().toString(36).substr(2, 9),
        title,
        type,
        dateRange,
        imageUrl,
        isNew: typeText.toLowerCase().includes('new'),
        // Add placeholders for metadata that we might find or need
        featured: []
      });
    });

    return items;
  });

  await browser.close();

  console.log(`Scraped ${banners.length} banners.`);

  const content = `// Generated by scripts/scrape_banners.mjs
export interface Banner {
  id: string;
  title: string;
  type: string;
  dateRange: string;
  imageUrl: string;
  isNew?: boolean;
  featured?: string[];
  metaRel?: string;
}

export const BANNERS: Banner[] = ${JSON.stringify(banners, null, 2)};
`;

  const outputPath = path.join(process.cwd(), 'src', 'data', 'banners.ts');
  fs.writeFileSync(outputPath, content);
  console.log(`Data saved to ${outputPath}`);
}

scrapeBanners().catch(console.error);
